In [1]:
import nlpia

In [2]:
from nlpia.data.loaders import get_data


/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pugnlp/constants.py:136: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  [datetime.datetime, pd.datetime, pd.Timestamp])
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pugnlp/constants.py:158: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  MIN_TIMESTAMP = pd.Timestamp(pd.datetime(1677, 9, 22, 0, 12, 44), tz='utc')
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pugnlp/tutil.py:100: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  np = pd.np
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pugnlp/util.py:80: FutureWarning: The pandas.np modul

In [3]:
movies = get_data('hutto_movies')

In [4]:
movies

sentiment                                               text
id                                                                 
1       2.266667  The Rock is destined to be the 21st Century's ...
2       3.533333  The gorgeously elaborate continuation of ''The...
3      -0.600000                     Effective but too tepid biopic
4       1.466667  If you sometimes like to go to the movies to h...
5       1.733333  Emerges as something rare, an issue movie that...
...          ...                                                ...
10601  -0.062500                        Well made but mush hearted.
10602  -1.500000                                     A real snooze.
10603  -0.625000                                      No surprises.
10604   1.437500  We’ve seen the hippie turned yuppie plot befor...
10605  -1.812500  Her fans walked out muttering words like ''hor...

[10605 rows x 2 columns]

In [5]:
movies.describe().round(2)

sentiment
count   10605.00
mean        0.00
std         1.92
min        -3.88
25%        -1.77
50%        -0.08
75%         1.83
max         3.94

In [6]:
movies.describe().round()

sentiment
count    10605.0
mean         0.0
std          2.0
min         -4.0
25%         -2.0
50%         -0.0
75%          2.0
max          4.0

In [7]:
import pandas as pd

In [8]:
pd.set_option('display.width', 75)

In [9]:
from nltk.tokenize import casual_tokenize

In [10]:
bags_of_words = []

In [14]:
from collections import Counter

In [15]:
movies.text

id
1        The Rock is destined to be the 21st Century's ...
2        The gorgeously elaborate continuation of ''The...
3                           Effective but too tepid biopic
4        If you sometimes like to go to the movies to h...
5        Emerges as something rare, an issue movie that...
                               ...                        
10601                          Well made but mush hearted.
10602                                       A real snooze.
10603                                        No surprises.
10604    We’ve seen the hippie turned yuppie plot befor...
10605    Her fans walked out muttering words like ''hor...
Name: text, Length: 10605, dtype: object

In [16]:
for text in movies.text:
    bags_of_words_append(Counter(casual_tokenize(text)))

NameError: name 'bags_of_words_append' is not defined

In [17]:
for text in movies.text:
    bags_of_words
    bags_of_words.append(Counter(casual_tokenize(text)))

In [18]:
    bags_of_words

[Counter({'The': 1,
          'Rock': 1,
          'is': 1,
          'destined': 1,
          'to': 2,
          'be': 1,
          'the': 1,
          '21st': 1,
          "Century's": 1,
          'new': 1,
          "'": 4,
          'Conan': 1,
          'and': 1,
          'that': 1,
          "he's": 1,
          'going': 1,
          'make': 1,
          'a': 1,
          'splash': 1,
          'even': 1,
          'greater': 1,
          'than': 1,
          'Arnold': 1,
          'Schwarzenegger': 1,
          ',': 1,
          'Jean': 1,
          'Claud': 1,
          'Van': 1,
          'Damme': 1,
          'or': 1,
          'Steven': 1,
          'Segal': 1,
          '.': 1}),
 Counter({'The': 2,
          'gorgeously': 1,
          'elaborate': 1,
          'continuation': 1,
          'of': 4,
          "'": 4,
          'Lord': 1,
          'the': 1,
          'Rings': 1,
          'trilogy': 1,
          'is': 1,
          'so': 1,
          'huge': 1,
          't

In [19]:
bags_of_words = []

In [20]:
bags_of_words

[]

In [21]:
for text in movies.text:
    bags_of_words.append(Counter(casual_tokenize(text)))

In [22]:
df_bows = pd.DataFrame.from_records(bags_of_words)

In [23]:
df_bows

The  Rock   is  destined   to   be  the  21st  Century's  new  \
0      1.0   1.0  1.0       1.0  2.0  1.0  1.0   1.0        1.0  1.0   
1      2.0   NaN  1.0       NaN  NaN  NaN  1.0   NaN        NaN  NaN   
2      NaN   NaN  NaN       NaN  NaN  NaN  NaN   NaN        NaN  NaN   
3      NaN   NaN  1.0       NaN  4.0  NaN  1.0   NaN        NaN  NaN   
4      NaN   NaN  NaN       NaN  NaN  NaN  NaN   NaN        NaN  NaN   
...    ...   ...  ...       ...  ...  ...  ...   ...        ...  ...   
10600  NaN   NaN  NaN       NaN  NaN  NaN  NaN   NaN        NaN  NaN   
10601  NaN   NaN  NaN       NaN  NaN  NaN  NaN   NaN        NaN  NaN   
10602  NaN   NaN  NaN       NaN  NaN  NaN  NaN   NaN        NaN  NaN   
10603  NaN   NaN  NaN       NaN  NaN  NaN  2.0   NaN        NaN  NaN   
10604  NaN   NaN  NaN       NaN  NaN  NaN  2.0   NaN        NaN  NaN   

       ...  Ill  slummer  Rashomon  dipsticks  Bearable  Staggeringly  \
0      ...  NaN      NaN       NaN        NaN       NaN           NaN   
1      ...  NaN      NaN       NaN        NaN       NaN           NaN   
2      ...  NaN      NaN       NaN        NaN       NaN           NaN   
3      ...  NaN      NaN       NaN        NaN       NaN           NaN   
4      ...  NaN      NaN       NaN        NaN       NaN           NaN   
...    ...  ...      ...       ...        ...       ...           ...   
10600  ...  NaN      NaN       NaN        NaN       NaN           NaN   
10601  ...  NaN      NaN       NaN        NaN       NaN           NaN   
10602  ...  NaN      NaN       NaN        NaN       NaN           NaN   
10603  ...  NaN      NaN       NaN        NaN       NaN           NaN   
10604  ...  NaN      NaN       NaN        NaN       NaN           NaN   

         ’   ve  muttering  dissing  
0      NaN  NaN        NaN      NaN  
1      NaN  NaN        NaN      NaN  
2      NaN  NaN        NaN      NaN  
3      NaN  NaN        NaN      NaN  
4      NaN  NaN        NaN      NaN  
...    ...  ...        ...      ...  
10600  NaN  NaN        NaN      NaN  
10601  NaN  NaN        NaN      NaN  
10602  NaN  NaN        NaN      NaN  
10603  2.0  1.0        NaN      NaN  
10604  NaN  NaN        1.0      1.0  

[10605 rows x 20756 columns]

In [24]:
df_bows = df_bows.fillna(0).astype(int)

In [25]:
df_bows

The  Rock  is  destined  to  be  the  21st  Century's  new  ...  \
0        1     1   1         1   2   1    1     1          1    1  ...   
1        2     0   1         0   0   0    1     0          0    0  ...   
2        0     0   0         0   0   0    0     0          0    0  ...   
3        0     0   1         0   4   0    1     0          0    0  ...   
4        0     0   0         0   0   0    0     0          0    0  ...   
...    ...   ...  ..       ...  ..  ..  ...   ...        ...  ...  ...   
10600    0     0   0         0   0   0    0     0          0    0  ...   
10601    0     0   0         0   0   0    0     0          0    0  ...   
10602    0     0   0         0   0   0    0     0          0    0  ...   
10603    0     0   0         0   0   0    2     0          0    0  ...   
10604    0     0   0         0   0   0    2     0          0    0  ...   

       Ill  slummer  Rashomon  dipsticks  Bearable  Staggeringly  ’  ve  \
0        0        0         0          0         0             0  0   0   
1        0        0         0          0         0             0  0   0   
2        0        0         0          0         0             0  0   0   
3        0        0         0          0         0             0  0   0   
4        0        0         0          0         0             0  0   0   
...    ...      ...       ...        ...       ...           ... ..  ..   
10600    0        0         0          0         0             0  0   0   
10601    0        0         0          0         0             0  0   0   
10602    0        0         0          0         0             0  0   0   
10603    0        0         0          0         0             0  2   1   
10604    0        0         0          0         0             0  0   0   

       muttering  dissing  
0              0        0  
1              0        0  
2              0        0  
3              0        0  
4              0        0  
...          ...      ...  
10600          0        0  
10601          0        0  
10602          0        0  
10603          0        0  
10604          1        1  

[10605 rows x 20756 columns]

In [26]:
df_bows.shape

(10605, 20756)

In [27]:
df_bows.head()

The  Rock  is  destined  to  be  the  21st  Century's  new  ...  Ill  \
0    1     1   1         1   2   1    1     1          1    1  ...    0   
1    2     0   1         0   0   0    1     0          0    0  ...    0   
2    0     0   0         0   0   0    0     0          0    0  ...    0   
3    0     0   1         0   4   0    1     0          0    0  ...    0   
4    0     0   0         0   0   0    0     0          0    0  ...    0   

   slummer  Rashomon  dipsticks  Bearable  Staggeringly  ’  ve  \
0        0         0          0         0             0  0   0   
1        0         0          0         0             0  0   0   
2        0         0          0         0             0  0   0   
3        0         0          0         0             0  0   0   
4        0         0          0         0             0  0   0   

   muttering  dissing  
0          0        0  
1          0        0  
2          0        0  
3          0        0  
4          0        0  

[5 rows x 20756 columns]

In [28]:
df_bows.head()[list(bags_of_words[0].keys())]

The  Rock  is  destined  to  be  the  21st  Century's  new  ...  \
0    1     1   1         1   2   1    1     1          1    1  ...   
1    2     0   1         0   0   0    1     0          0    0  ...   
2    0     0   0         0   0   0    0     0          0    0  ...   
3    0     0   1         0   4   0    1     0          0    0  ...   
4    0     0   0         0   0   0    0     0          0    0  ...   

   Schwarzenegger  ,  Jean  Claud  Van  Damme  or  Steven  Segal  .  
0               1  1     1      1    1      1   1       1      1  1  
1               0  0     0      0    0      0   0       0      0  4  
2               0  0     0      0    0      0   0       0      0  0  
3               0  1     0      0    0      0   0       0      0  1  
4               0  1     0      0    0      0   0       0      0  1  

[5 rows x 33 columns]

In [43]:
from sklearn.naive_bayes import MultinomialNB

In [44]:
nb = []

In [45]:
nb = MultinomialNB

In [46]:
nb

sklearn.naive_bayes.MultinomialNB

In [47]:
nb = MultinomialNB()

In [48]:
nb = nb.fit(df_bows, movies.predicted_sentiment - movies.sentiment).absa()

AttributeError: 'DataFrame' object has no attribute 'predicted_sentiment'

In [49]:
movies

sentiment                                               text
id                                                                 
1       2.266667  The Rock is destined to be the 21st Century's ...
2       3.533333  The gorgeously elaborate continuation of ''The...
3      -0.600000                     Effective but too tepid biopic
4       1.466667  If you sometimes like to go to the movies to h...
5       1.733333  Emerges as something rare, an issue movie that...
...          ...                                                ...
10601  -0.062500                        Well made but mush hearted.
10602  -1.500000                                     A real snooze.
10603  -0.625000                                      No surprises.
10604   1.437500  We’ve seen the hippie turned yuppie plot befor...
10605  -1.812500  Her fans walked out muttering words like ''hor...

[10605 rows x 2 columns]

In [50]:
movies.predicted_sentiment

AttributeError: 'DataFrame' object has no attribute 'predicted_sentiment'

In [51]:
nb = nb.fit(df_bows, movies.sentiment > 0)

In [52]:
movies['predicted_sentiment'] = \
nb.predict_proba(df_bows) * 8 - 4

ValueError: Wrong number of items passed 2, placement implies 1

In [53]:
movies['predicted_sentiment'] = 
nb.predict_proba(df_bows) * 8 - 4

SyntaxError: invalid syntax (<ipython-input-53-c8943383522c>, line 1)

In [54]:
movies['predicted_sentiment'] = \nb.predict_proba(df_bows) * 8 - 4

SyntaxError: unexpected character after line continuation character (<ipython-input-54-d96e38ef5d13>, line 1)

In [55]:
movies['predicted_sentiment'] = nb.predict_proba(df_bows) * 8 - 4

ValueError: Wrong number of items passed 2, placement implies 1

In [56]:
df_bows.shape

(10605, 20756)

In [57]:
movies.describe().round(2)

sentiment
count   10605.00
mean        0.00
std         1.92
min        -3.88
25%        -1.77
50%        -0.08
75%         1.83
max         3.94

In [58]:
nb.predict_proba(df_bows)

array([[1.86060657e-01, 8.13939343e-01],
       [1.19745717e-05, 9.99988025e-01],
       [9.56997000e-01, 4.30029997e-02],
       ...,
       [6.85181156e-01, 3.14818844e-01],
       [1.37651091e-03, 9.98623489e-01],
       [9.99744277e-01, 2.55722778e-04]])

In [59]:
movies['predicted_sentiment'] = []

ValueError: Length of values (0) does not match length of index (10605)

In [60]:
movies['predicted_sentiment'] = [10605]

ValueError: Length of values (1) does not match length of index (10605)

In [61]:
v=nb.predict_proba(df_bows)

In [62]:
v.shape()

TypeError: 'tuple' object is not callable

In [63]:
v

array([[1.86060657e-01, 8.13939343e-01],
       [1.19745717e-05, 9.99988025e-01],
       [9.56997000e-01, 4.30029997e-02],
       ...,
       [6.85181156e-01, 3.14818844e-01],
       [1.37651091e-03, 9.98623489e-01],
       [9.99744277e-01, 2.55722778e-04]])

In [72]:
v.shape

(10605, 2)

In [73]:
b = nb.predict_proba(df_bows) * 8 - 4 

In [74]:
b

array([[-2.51151475,  2.51151475],
       [-3.9999042 ,  3.9999042 ],
       [ 3.655976  , -3.655976  ],
       ...,
       [ 1.48144924, -1.48144924],
       [-3.98898791,  3.98898791],
       [ 3.99795422, -3.99795422]])

In [75]:
b.size

21210

In [76]:
b.shape

(10605, 2)

In [77]:
b[:,]

array([[-2.51151475,  2.51151475],
       [-3.9999042 ,  3.9999042 ],
       [ 3.655976  , -3.655976  ],
       ...,
       [ 1.48144924, -1.48144924],
       [-3.98898791,  3.98898791],
       [ 3.99795422, -3.99795422]])

In [78]:
x = b[:,1]

In [79]:
x

array([ 2.51151475,  3.9999042 , -3.655976  , ..., -1.48144924,
        3.98898791, -3.99795422])

In [80]:
movies['predicted_sentiment'] = x * 8 - 4 

In [81]:
movies.predicted_sentiment

id
1        16.092118
2        27.999234
3       -33.247808
4        11.527632
5        27.282985
           ...    
10601   -29.331909
10602   -12.454440
10603   -15.851594
10604    27.911903
10605   -35.983634
Name: predicted_sentiment, Length: 10605, dtype: float64

In [82]:
movies['predicted_sentiment'] =\ x * 8 - 4 

SyntaxError: unexpected character after line continuation character (<ipython-input-82-fc91bc7925ef>, line 1)

In [85]:
movies['predicted_sentiment'] =\ 
x * 8 - 4 

SyntaxError: unexpected character after line continuation character (<ipython-input-85-a5c969ef2297>, line 1)

In [86]:
movies['predicted_sentiment'] = x 

In [87]:
movies['error'] = (movies.predicted_sentiment - movies .sentiment).abs()
movies.error.mean().round(1)

1.9

In [88]:
nb = nb.fit(df_bows, movies.sentiment > 0)

In [89]:
x = nb.predict_proba(df_bows)

In [90]:
x

array([[1.86060657e-01, 8.13939343e-01],
       [1.19745717e-05, 9.99988025e-01],
       [9.56997000e-01, 4.30029997e-02],
       ...,
       [6.85181156e-01, 3.14818844e-01],
       [1.37651091e-03, 9.98623489e-01],
       [9.99744277e-01, 2.55722778e-04]])

In [91]:
x.shape

(10605, 2)

In [92]:
movies['predicted_sentiment'] =\ 
x * 8 - 4 

SyntaxError: unexpected character after line continuation character (<ipython-input-92-a5c969ef2297>, line 1)

In [93]:
movies['predicted_sentiment'] = x * 8 - 4 

In [94]:
movies

sentiment                                               text  \
id                                                                    
1       2.266667  The Rock is destined to be the 21st Century's ...   
2       3.533333  The gorgeously elaborate continuation of ''The...   
3      -0.600000                     Effective but too tepid biopic   
4       1.466667  If you sometimes like to go to the movies to h...   
5       1.733333  Emerges as something rare, an issue movie that...   
...          ...                                                ...   
10601  -0.062500                        Well made but mush hearted.   
10602  -1.500000                                     A real snooze.   
10603  -0.625000                                      No surprises.   
10604   1.437500  We’ve seen the hippie turned yuppie plot befor...   
10605  -1.812500  Her fans walked out muttering words like ''hor...   

       predicted_sentiment     error  
id                                    
1                -2.511515  0.244848  
2                -3.999904  0.466571  
3                 3.655976  3.055976  
4                -1.940954  0.474287  
5                -3.910373  2.177040  
...                    ...       ...  
10601             3.166489  3.103989  
10602             1.056805  0.443195  
10603             1.481449  0.856449  
10604            -3.988988  2.551488  
10605             3.997954  2.185454  

[10605 rows x 4 columns]

In [96]:
movies['error'] = (movies.predicted_sentiment - movies.sentiment).abs()

In [97]:
movies

sentiment                                               text  \
id                                                                    
1       2.266667  The Rock is destined to be the 21st Century's ...   
2       3.533333  The gorgeously elaborate continuation of ''The...   
3      -0.600000                     Effective but too tepid biopic   
4       1.466667  If you sometimes like to go to the movies to h...   
5       1.733333  Emerges as something rare, an issue movie that...   
...          ...                                                ...   
10601  -0.062500                        Well made but mush hearted.   
10602  -1.500000                                     A real snooze.   
10603  -0.625000                                      No surprises.   
10604   1.437500  We’ve seen the hippie turned yuppie plot befor...   
10605  -1.812500  Her fans walked out muttering words like ''hor...   

       predicted_sentiment     error  
id                                    
1                -2.511515  4.778181  
2                -3.999904  7.533238  
3                 3.655976  4.255976  
4                -1.940954  3.407621  
5                -3.910373  5.643706  
...                    ...       ...  
10601             3.166489  3.228989  
10602             1.056805  2.556805  
10603             1.481449  2.106449  
10604            -3.988988  5.426488  
10605             3.997954  5.810454  

[10605 rows x 4 columns]

In [98]:
movies.error.mean().round(1)

5.0

In [99]:
movies['predicted_sentiment'] = nb.predict_proba(df_bows) * 8 - 4 

In [100]:
movies

sentiment                                               text  \
id                                                                    
1       2.266667  The Rock is destined to be the 21st Century's ...   
2       3.533333  The gorgeously elaborate continuation of ''The...   
3      -0.600000                     Effective but too tepid biopic   
4       1.466667  If you sometimes like to go to the movies to h...   
5       1.733333  Emerges as something rare, an issue movie that...   
...          ...                                                ...   
10601  -0.062500                        Well made but mush hearted.   
10602  -1.500000                                     A real snooze.   
10603  -0.625000                                      No surprises.   
10604   1.437500  We’ve seen the hippie turned yuppie plot befor...   
10605  -1.812500  Her fans walked out muttering words like ''hor...   

       predicted_sentiment     error  
id                                    
1                -2.511515  4.778181  
2                -3.999904  7.533238  
3                 3.655976  4.255976  
4                -1.940954  3.407621  
5                -3.910373  5.643706  
...                    ...       ...  
10601             3.166489  3.228989  
10602             1.056805  2.556805  
10603             1.481449  2.106449  
10604            -3.988988  5.426488  
10605             3.997954  5.810454  

[10605 rows x 4 columns]

In [101]:
movies['predicted_sentiment'] = - nb.predict_proba(df_bows) * 8 - 4 

In [102]:
movies

sentiment                                               text  \
id                                                                    
1       2.266667  The Rock is destined to be the 21st Century's ...   
2       3.533333  The gorgeously elaborate continuation of ''The...   
3      -0.600000                     Effective but too tepid biopic   
4       1.466667  If you sometimes like to go to the movies to h...   
5       1.733333  Emerges as something rare, an issue movie that...   
...          ...                                                ...   
10601  -0.062500                        Well made but mush hearted.   
10602  -1.500000                                     A real snooze.   
10603  -0.625000                                      No surprises.   
10604   1.437500  We’ve seen the hippie turned yuppie plot befor...   
10605  -1.812500  Her fans walked out muttering words like ''hor...   

       predicted_sentiment     error  
id                                    
1                -5.488485  4.778181  
2                -4.000096  7.533238  
3               -11.655976  4.255976  
4                -6.059046  3.407621  
5                -4.089627  5.643706  
...                    ...       ...  
10601           -11.166489  3.228989  
10602            -9.056805  2.556805  
10603            -9.481449  2.106449  
10604            -4.011012  5.426488  
10605           -11.997954  5.810454  

[10605 rows x 4 columns]

In [103]:
movies['predicted_sentiment'] = - (nb.predict_proba(df_bows) * 8 - 4) 

In [104]:
movies

sentiment                                               text  \
id                                                                    
1       2.266667  The Rock is destined to be the 21st Century's ...   
2       3.533333  The gorgeously elaborate continuation of ''The...   
3      -0.600000                     Effective but too tepid biopic   
4       1.466667  If you sometimes like to go to the movies to h...   
5       1.733333  Emerges as something rare, an issue movie that...   
...          ...                                                ...   
10601  -0.062500                        Well made but mush hearted.   
10602  -1.500000                                     A real snooze.   
10603  -0.625000                                      No surprises.   
10604   1.437500  We’ve seen the hippie turned yuppie plot befor...   
10605  -1.812500  Her fans walked out muttering words like ''hor...   

       predicted_sentiment     error  
id                                    
1                 2.511515  4.778181  
2                 3.999904  7.533238  
3                -3.655976  4.255976  
4                 1.940954  3.407621  
5                 3.910373  5.643706  
...                    ...       ...  
10601            -3.166489  3.228989  
10602            -1.056805  2.556805  
10603            -1.481449  2.106449  
10604             3.988988  5.426488  
10605            -3.997954  5.810454  

[10605 rows x 4 columns]

In [105]:
movies['error'] = (movies.predicted_sentiment - movies.sentiment).abs()
movies.error.mean().round(1)

1.9

In [106]:
movies['sentiment_ispositive'] = (movies.sentiment > 0).astype(int)

In [107]:
movies['predicted_ispositiv'] = (movies.predicted_sentiment > 0).astype(int)

In [108]:
movies['''sentiment predicted_sentiment sentiment_ispositive predicted_ispositive'''.split()].head(8)

KeyError: "['predicted_ispositive'] not in index"

In [109]:
movies['''sentiment predicted_sentiment sentiment_ispositive predicted_ispositiv'''.split()].head(8)

sentiment  predicted_sentiment  sentiment_ispositive  \
id                                                         
1    2.266667             2.511515                     1   
2    3.533333             3.999904                     1   
3   -0.600000            -3.655976                     0   
4    1.466667             1.940954                     1   
5    1.733333             3.910373                     1   
6    2.533333             3.995188                     1   
7    2.466667             3.960466                     1   
8    1.266667            -1.918701                     1   

    predicted_ispositiv  
id                       
1                     1  
2                     1  
3                     0  
4                     1  
5                     1  
6                     1  
7                     1  
8                     0

In [112]:
(movies.predicted_ispositiv == movies.predicted_ispositiv).sum()/ len(movies)

1.0

In [114]:
(movies.predicted_ispositiv == movies.sentiment_ispositive).sum()/ len(movies)

0.9344648750589345